const ThemeCss = {
  cascade: ":root { --primary: violet; }",
  incomplete: ":root { --background: white; }",
  invalid: ":root {",
  valid: `:root {
    --background: white;
    --foreground: black;
    --card: ivory;
    --primary: purple;
    --muted-foreground: gray;
    --border: silver;
    --success: green;
    --destructive: red;
    color: orange;
  }
  [data-theme="dark"] { --background: black; --foreground: white; }
  .unrelated { --background: pink; }`,
} as const;

// These literal expectations describe CSS inheritance and the cascade. They
// are not generated by parseTheme or by the production token list.
const ThemeExpected = {
  dark: {
    background: "black",
    foreground: "white",
    primary: "purple",
    success: "green",
  },
  light: {
    background: "white",
    border: "silver",
    card: "ivory",
    destructive: "red",
    foreground: "black",
    "muted-foreground": "gray",
    primary: "purple",
    success: "green",
  },
  override: "violet",
} as const;

const ThemeCases = {
  cascade:
    "Applies later declarations to both themes unless dark overrides them.",
  colors: "Extracts CSS variables and inherits missing dark theme tokens.",
  incomplete:
    "Rejects an incomplete light palette through the Effect error channel.",
  invalid: "Preserves the parser failure for malformed CSS.",
  suite: "Theme palettes.",
} as const;

const LoaderFiles = {
  css: "app/globals.css",
  source: "lib/theme/theme.source.ts",
} as const;
const LoaderCases = {
  missing: "Reports a missing stylesheet instead of emitting an empty module.",
  reload:
    "Registers the stylesheet and reads its new contents on the next load.",
  suite: "Theme loader.",
} as const;
const LoaderModule = { dataPrefix: "data:text/javascript;base64," } as const;

export {
  LoaderCases,
  LoaderFiles,
  LoaderModule,
  ThemeCases,
  ThemeCss,
  ThemeExpected,
};
